FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y software-properties-common \
                   debmake \
                   equivs \
                   git \
                   gpg \
                   debhelper \
                   bison \
                   cmake \
                   flex \
                   libapr1-dev \
                   libbz2-dev \
                   libcurl4-gnutls-dev \
                   libevent-dev \
                   libkrb5-dev \
                   libldap2-dev \
                   libperl-dev \
                   libreadline6-dev \
                   libssl-dev \
                   libxml2-dev \
                   libyaml-dev \
                   ninja-build \
                   python-dev \
                   python-setuptools \
                   zlib1g-dev
